language: c

sudo: required


env:
  - TRAVIS=true
  - DEBIAN_FRONTEND=noninteractive


sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

before_install:
  - docker run -d --name ubuntu-test -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $SH "apt-get update -qq"
  - $SH "apt-get install -y locales"
  - $SH "locale-gen en_US.UTF-8"
  - $SH "env DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common make gcc-7 gnat-7 gprbuild"

script:
  - $SH " bash -eux .travis-ci.sh"

notifications:
    email: false
